require:
  - '@babel/register'
  - 'babel-polyfill'

reporter: spec

extension:
  - js
  - jsx

spec: 
  - '**/*.test.js'
  - '**/*.test.jsx'

watch: true
watch-files:
  - 'src/**/*.test.js'
  - 'src/**/*.test.jsx'

async-only: true